### ISSUE TITLE
-H option before url leads to no url being specified

### ISSUE THREAD

**Issue by jelly** [hatoo/oha#131]
When trying out oha with a custom header before the url it throws an error that no url is provided:
```
oha -n 100 -H "Authorization: Bearer $TOKEN_VALUE"  'https://github.com/llala'
error: The following required arguments were not provided:
    <url>

USAGE:
    oha [FLAGS] [OPTIONS] <url>

For more information try --help
```
As headers takes a Vec<String> the url is parsed as a header which is unexpected, the following options do work:
```
oha  -H "Authorization: Bearer $TOKEN_VALUE"  -n 100 'https://github.com/llala'
oha  -n 100 'https://github.com/llala'  -H "Authorization: Bearer $TOKEN_VALUE"  
```

The simple "fix" would be to make -H not take a vec<String> but a Option<String> and let users append -H multiple times to set multiple headers. But this will break existing users workflow, as alternative maybe allow users to provide the url as parameter?
Or structopt could verify if the provided argument was an valid HTTP header, but that might add more complexity.

**Comment by hatoo** [comment]
You can use `--` to end flags.
`oha -n 100 -H "Authorization: Bearer $TOKEN_VALUE" -- 'https://github.com/llala'` works.

I think let users append -H multiple times to set multiple headers is OK because it's what `rakyll/hey` does.
I've found that the feature is implemented in [new clap](https://docs.rs/clap/3.0.0-beta.2/clap/struct.Arg.html#method.multiple_occurrences) but we can't use it from `structopt` yet because `structopt` depends on `clap` 2.x.
